### ISSUE TITLE
No Crash but Problems with the Mod and Forge 35.0.18

### ISSUE THREAD

**Issue by cyberpunkbln** [Kotori316/FluidTank#65]
Hello,

i have a problem. When i put an Fluid Tank on the ground and break it with hand or pickaxe he disapears and leave an invisible block back. A block where i can only slowly go trough.

I have downloaded the latest mixin fix 6.0.7 and when i start my world all Tanks that i have set appears at the position where i have breaked the Tanks.

When i want to break there disappears again and when i put an cobblestone into the air-block then the tank appears back.

New Worlds the same bug.

LargeFluidTank-16.0.7.jar
ScalableCatsForce-2.13.3-build-6-with-library.jar

?

Sorry my debug.log is very huge:
Is that helpfull?:

```
[17Nov2020 19:13:48.225] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Neue Welt]'/minecraft:overworld
[17Nov2020 19:13:48.343] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Neue Welt]'/minecraft:the_nether
[17Nov2020 19:13:48.344] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Neue Welt]'/minecraft:the_end
[17Nov2020 19:13:48.345] [Server thread/DEBUG] [net.minecraftforge.fml.FMLWorldPersistenceHook/WP]: Gathering id map for writing to world save Neue Welt
[17Nov2020 19:13:48.361] [Server thread/DEBUG] [net.minecraftforge.fml.FMLWorldPersistenceHook/WP]: ID Map collection complete Neue Welt
[17Nov2020 19:13:56.259] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Supplier is empty. Mixin system for `kotori_scala`(Scalable Cats Force) seems not working.
	Index: 3
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2962/557331894@25859c6c
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2962/557331894@4644310f
		3: ASM: com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeListener@4b186fa9 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		4: LOW
		5: ASM: class cofh.core.event.AreaEffectEvents handleBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		6: LOWEST
		7: ASM: blusunrize.immersiveengineering.common.EventHandler@249f04cb breakLast(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
java.util.NoSuchElementException: Supplier is empty. Mixin system for `kotori_scala`(Scalable Cats Force) seems not working.
	at com.kotori316.scala_lib.util.LazySupplierWrapper.$anonfun$get$1(LazySupplierWrapper.scala:10)
	at com.kotori316.scala_lib.util.LazySupplierWrapper$$Lambda$14948/460780589.apply(Unknown Source)
	at scala.Option.getOrElse(Option.scala:201)
	at cats.data.OptionT.$anonfun$getOrElse$1(OptionT.scala:99)
	at cats.data.OptionT$$Lambda$14949/1308840668.apply(Unknown Source)
	at cats.Eval.$anonfun$map$1(Eval.scala:57)
	at cats.Eval$$Lambda$14950/1335617772.apply(Unknown Source)
	at cats.Eval$.loop$1(Eval.scala:358)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:363)
	at cats.Eval$FlatMap.value(Eval.scala:284)
	at com.kotori316.scala_lib.util.LazySupplierWrapper.get(LazySupplierWrapper.scala:10)
	at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:116)
	at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:250)
	at com.refinedmods.refinedstorage.util.NetworkUtils.getNodeFromTile(NetworkUtils.java:27)
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeListener.onBlockBreak(NetworkNodeListener.java:58)
	at net.minecraftforge.eventbus.ASMEventHandler_518_NetworkNodeListener_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:561)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230)
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220)
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34)
	at net.minecraft.network.PacketThreadUtil$$Lambda$14334/711769512.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$13482/1545377456.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[17Nov2020 19:13:56.260] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.util.NoSuchElementException: Supplier is empty. Mixin system for `kotori_scala`(Scalable Cats Force) seems not working.
	at com.kotori316.scala_lib.util.LazySupplierWrapper.$anonfun$get$1(LazySupplierWrapper.scala:10) ~[?:2.13.3-build-6]
	at com.kotori316.scala_lib.util.LazySupplierWrapper$$Lambda$14948/460780589.apply(Unknown Source) ~[?:?]
	at scala.Option.getOrElse(Option.scala:201) ~[?:2.13.3-build-6]
	at cats.data.OptionT.$anonfun$getOrElse$1(OptionT.scala:99) ~[?:2.13.3-build-6]
	at cats.data.OptionT$$Lambda$14949/1308840668.apply(Unknown Source) ~[?:?]
	at cats.Eval.$anonfun$map$1(Eval.scala:57) ~[?:2.13.3-build-6]
	at cats.Eval$$Lambda$14950/1335617772.apply(Unknown Source) ~[?:?]
	at cats.Eval$.loop$1(Eval.scala:358) ~[?:2.13.3-build-6]
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:363) ~[?:2.13.3-build-6]
	at cats.Eval$FlatMap.value(Eval.scala:284) ~[?:2.13.3-build-6]
	at com.kotori316.scala_lib.util.LazySupplierWrapper.get(LazySupplierWrapper.scala:10) ~[?:2.13.3-build-6]
	at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:116) ~[?:?]
	at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:250) ~[?:?]
	at com.refinedmods.refinedstorage.util.NetworkUtils.getNodeFromTile(NetworkUtils.java:27) ~[?:1.9.9]
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeListener.onBlockBreak(NetworkNodeListener.java:58) ~[?:1.9.9]
	at net.minecraftforge.eventbus.ASMEventHandler_518_NetworkNodeListener_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:561) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$14334/711769512.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$13482/1545377456.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by cyberpunkbln** [comment]
Ah i have found the mod that interference with FluidTank and Scala, it is Refined Storage.
refinedstorage-1.9.9.jar

**Comment by cyberpunkbln** [comment]
Must i me decide between Refined Storage and Large Fluid Tank. The answer i have received is that Scala is the failure.
Ist that fixable in the scala-mod?
[https://github.com/refinedmods/refinedstorage/issues/2745](https://github.com/refinedmods/refinedstorage/issues/2745)

**Comment by Kotori316** [comment]
In my environment, the problem didn't happen with Forge 35.0.18, Tank 16.0.7, Scalable Cats Force 2.13.3 build 6.

Add `-Dmixin.debug=true` as java parameter to check a directory, `.mixin.out/class`, ill be made.

**Comment by cyberpunkbln** [comment]
Hello,

i have updated Forge to 35.0.18 before i installed Tank, after the bug with the tanks i have seen after refresh curseforge there is a scale and tank version that focused on the mixin problems with forge 35.0.16-18.

Right a pure Installation of only the affected mods Forge 35.0.18, Tank 16.0.7, Scalable Cats Force 2.13.3 build 6 don't trigger the error.

When i load all 97 mods (very hard to debug, while every mod can it be and when i del refined storage all fine, but it seems another mod is the problem but when i del refined storage all fine, i wrote, hmm strange).

This are the debug,log with all 97 mods and refined storage loaded and zipped version of -Dmixin.debug=true.

[latest.log](https://github.com/Kotori316/FluidTank/files/5559310/latest.log)
[debug.log](https://github.com/Kotori316/FluidTank/files/5559311/debug.log)
[mixin.out.zip](https://github.com/Kotori316/FluidTank/files/5559321/mixin.out.zip)

At the moment i use my small user knowledge and try to find out the mods that trigger the mod with refined storage installed.

**Comment by cyberpunkbln** [comment]
btw:
What do you mean with 

> If found, you'll never see the error. If not, you may have installed wrong version.

When i delete Refined Storage and i use Tanks the debug.log/latest.log Message don't appear but the Scala error message doesn't appear and all functioned perfectly without Refined Storage.

Sorry but this message i cannot use for debugging.

> [main/INFO] [mixin/]: Selecting config slp.mixins.json
> [main/INFO] [mixin/]: Preparing slp.mixins.json (1)

Many mods break this message but functioned well with Tanks.

Puh i have many Mod-Constellation tested i don't found or to many constellations of mods are not compatible with Scala.
At the moment i hope my Attachments in the previous Post can help, but it looks like i must delete many many many mods from my Modpack or i must delete Scala and Tanks. Seufz LFF ist at the moment the only Tankmod:(.

**Comment by Kotori316** [comment]
I uploaded [v16.0.8](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/3115568).
I changed code not to use the supplier to avoid mixin error.

**Comment by cyberpunkbln** [comment]
Yes that it is, i can use tanks without bug and with Refined Storage.
Thx for the bugfixing.
