### ISSUE TITLE
[1.18.2] Incompat with Create causing resourcepacks to fail

### ISSUE THREAD

**Issue by itsdinkd** [Kotori316/FluidTank#97]
fluid tank version 18.5.0
create version 0.4.1+637

```java
[14:51:31] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.ClassCastException: class com.kotori316.fluidtank.milk.MilkFluid cannot be cast to class net.minecraft.class_3609 (com.kotori316.fluidtank.milk.MilkFluid and net.minecraft.class_3609 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2473b9ce)
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:68) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:68) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:68) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:68) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:68) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:68) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:68) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem:211) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:198) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1147) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ClassCastException: class com.kotori316.fluidtank.milk.MilkFluid cannot be cast to class net.minecraft.class_3609 (com.kotori316.fluidtank.milk.MilkFluid and net.minecraft.class_3609 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2473b9ce)
	at io.github.fabricators_of_create.porting_lib.util.PortingHooks.getFluidAttributesFromVariant(PortingHooks.java:126) ~[porting_lib-1.2.415-beta+1.18.2-dev.32355d3-d98a58e1fd51a9bb.jar:?]
	at io.github.fabricators_of_create.porting_lib.extensions.FluidExtensions.createVanillaFluidAttributes(FluidExtensions.java:39) ~[porting_lib-1.2.415-beta+1.18.2-dev.32355d3-d98a58e1fd51a9bb.jar:?]
	at io.github.fabricators_of_create.porting_lib.extensions.FluidExtensions.createAttributes(FluidExtensions.java:46) ~[porting_lib-1.2.415-beta+1.18.2-dev.32355d3-d98a58e1fd51a9bb.jar:?]
	at net.minecraft.fluid.Fluid.getAttributes(Fluid:539) ~[?:?]
	at io.github.fabricators_of_create.porting_lib.PortingLibClient.lambda$onInitializeClient$2(PortingLibClient.java:39) ~[porting_lib-1.2.415-beta+1.18.2-dev.32355d3-d98a58e1fd51a9bb.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.fabricators_of_create.porting_lib.PortingLibClient.lambda$onInitializeClient$3(PortingLibClient.java:38) ~[porting_lib-1.2.415-beta+1.18.2-dev.32355d3-d98a58e1fd51a9bb.jar:?]
	at io.github.fabricators_of_create.porting_lib.event.client.ModelsBakedCallback.lambda$static$0(ModelsBakedCallback.java:18) ~[porting_lib-1.2.415-beta+1.18.2-dev.32355d3-d98a58e1fd51a9bb.jar:?]
	at net.minecraft.client.render.model.BakedModelManager.handler$zbl000$port_lib$onModelBake(BakedModelManager:530) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:72) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 73 more
```

**Comment by Kotori316** [comment]
Fixed in the latest version, but I didn't test it because I don't know which mod provides these APIs.

**Comment by itsdinkd** [comment]
Testing now, thanks
